# Generated by Django 4.1 on 2022-08-18 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, verbose_name='Название города')),
            ],
            options={
                'verbose_name': 'Города',
                'verbose_name_plural': 'Город',
                'db_table': 'town',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, verbose_name='Название города')),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.town', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Улицы',
                'verbose_name_plural': 'Улица',
                'db_table': 'street',
                'ordering': ['town'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, verbose_name='Название магазина')),
                ('house', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер дома')),
                ('opening_time', models.TimeField(blank=True, verbose_name='Время открытия')),
                ('closing_time', models.TimeField(blank=True, verbose_name='Время закрытия')),
                ('street', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.street', verbose_name='Улица')),
                ('town', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.town', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Магазины',
                'verbose_name_plural': 'Магазин',
                'db_table': 'shop',
                'ordering': ['name'],
            },
        ),
    ]
